const canvas=document.querySelector('#network'),ctx=canvas.getContext('2d'),panel=canvas.parentElement,motionButton=document.querySelector('#motion');
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches,width=0,height=0,time=0,last=0,frame=0;const pointer={x:0,y:0};
function resize(){const box=panel.getBoundingClientRect();width=box.width;height=box.height;const ratio=Math.min(devicePixelRatio||1,2);canvas.width=width*ratio;canvas.height=height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);draw();}
function draw(){ctx.clearRect(0,0,width,height);const cx=width/2+pointer.x*13,cy=height/2+pointer.y*13,r=Math.min(width,height)*.32;const nodes=[];for(let i=0;i<8;i++){const angle=i*Math.PI/4+time*.045;nodes.push({x:cx+Math.cos(angle)*r*(i%2?1:.88),y:cy+Math.sin(angle)*r});}ctx.strokeStyle='#71845530';ctx.lineWidth=1;[.62,1,1.23].forEach(scale=>{ctx.beginPath();ctx.ellipse(cx,cy,r*scale,r*scale,0,0,Math.PI*2);ctx.stroke();});nodes.forEach((n,i)=>{ctx.strokeStyle='#a5cf6745';ctx.beginPath();ctx.moveTo(n.x,n.y);ctx.lineTo(cx,cy);ctx.lineTo(nodes[(i+3)%8].x,nodes[(i+3)%8].y);ctx.stroke();const f=(time*.16+i*.123)%1;ctx.fillStyle='#c2f66b';ctx.beginPath();ctx.arc(n.x+(cx-n.x)*f,n.y+(cy-n.y)*f,2,0,Math.PI*2);ctx.fill();ctx.fillStyle='#1f2919';ctx.strokeStyle='#a9db6b';ctx.beginPath();ctx.arc(n.x,n.y,i%2?6:9,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#c2f66b';ctx.fillRect(n.x-1.5,n.y-1.5,3,3);});ctx.save();ctx.translate(cx,cy);ctx.rotate(Math.PI/4);ctx.fillStyle='#1d2618';ctx.shadowColor='#b6f16b';ctx.shadowBlur=22;ctx.strokeStyle='#b6ed75';ctx.strokeRect(-48,-48,96,96);ctx.shadowBlur=0;ctx.fillRect(-47,-47,94,94);ctx.restore();}
function loop(stamp){if(paused){frame=0;return;}time+=Math.min((stamp-last)/1000,.04);last=stamp;draw();frame=requestAnimationFrame(loop);}
function sync(){motionButton.textContent=paused?'Resume motion ▷':'Pause motion Ⅱ';motionButton.setAttribute('aria-pressed',String(paused));if(paused){cancelAnimationFrame(frame);frame=0;pointer.x=pointer.y=0;draw();document.querySelectorAll('.project').forEach(c=>c.style.transform='');}else if(!frame){last=performance.now();frame=requestAnimationFrame(loop);}}
motionButton.addEventListener('click',()=>{paused=!paused;sync();});reduced.addEventListener('change',()=>{paused=reduced.matches;sync();});
document.addEventListener('pointermove',e=>{if(paused||e.pointerType==='touch')return;pointer.x=(e.clientX/window.innerWidth-.5)*2;pointer.y=(e.clientY/window.innerHeight-.5)*2;const glow=document.querySelector('.cursor-glow');glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px';});
document.querySelectorAll('.project').forEach(card=>{card.addEventListener('pointermove',e=>{if(paused||e.pointerType==='touch')return;const b=card.getBoundingClientRect(),x=(e.clientX-b.left)/b.width-.5,y=(e.clientY-b.top)/b.height-.5;card.style.transform=`perspective(900px) rotateX(${-y*5}deg) rotateY(${x*5}deg) translateY(-3px)`;});card.addEventListener('pointerleave',()=>card.style.transform='');});
document.querySelector('#year').textContent=new Date().getFullYear();new ResizeObserver(resize).observe(panel);resize();sync();
